# Generated by Django 4.2.17 on 2025-12-31 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feed Group',
                'verbose_name_plural': 'Feed Groups',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aggregator', models.CharField(choices=[('full_website', 'Full Website'), ('feed_content', 'Feed Content (RSS/Atom)'), ('heise', 'Heise'), ('merkur', 'Merkur'), ('tagesschau', 'Tagesschau'), ('explosm', 'Explosm'), ('dark_legacy', 'Dark Legacy Comics'), ('caschys_blog', "Caschy's Blog"), ('mactechnews', 'MacTechNews'), ('oglaf', 'Oglaf'), ('mein_mmo', 'Mein-MMO'), ('youtube', 'YouTube'), ('reddit', 'Reddit'), ('podcast', 'Podcast')], default='full_website', max_length=50)),
                ('identifier', models.TextField(help_text='URL, subreddit, or channel identifier')),
                ('daily_limit', models.IntegerField(default=50)),
                ('enabled', models.BooleanField(default=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='core.feedgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('identifier', models.TextField()),
                ('raw_content', models.TextField(help_text='Raw HTML content')),
                ('content', models.TextField(help_text='Processed content')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.feed')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['user'], name='core_feed_user_id_b5e9be_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['group'], name='core_feed_group_i_43683c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'identifier'], name='core_articl_feed_id_4eb94b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'date'], name='core_articl_feed_id_13f1da_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['date'], name='core_articl_date_304ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['read'], name='core_articl_read_0e838a_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['starred'], name='core_articl_starred_f4b11d_idx'),
        ),
    ]
