# Generated by Django 6.0 on 2026-01-01 10:32

from django.db import migrations
from django.contrib.auth.models import User
from django.utils import timezone


def create_admin_user(apps, schema_editor):
    if not User.objects.filter(username='admin').exists():
        user = User.objects.create_superuser('admin', 'admin@example.com', 'admin')
        user.last_login = timezone.now()
        user.save()


def reverse_admin_user(apps, schema_editor):
    User.objects.filter(username='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_admin_user),
    ]
