# Generated by Django 6.0 on 2026-01-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_article_author_alter_article_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GReaderAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greader_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Reader Auth Token',
                'verbose_name_plural': 'Google Reader Auth Tokens',
                'indexes': [models.Index(fields=['token'], name='core_greade_token_ec6b6b_idx'), models.Index(fields=['user'], name='core_greade_user_id_ccd9f7_idx')],
            },
        ),
    ]
