# Generated by Django 6.0 on 2026-01-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_greaderauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='article_icons/'),
        ),
    ]
