# Generated by Django 6.0 on 2026-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_user_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='core_userse_user_id_abe139_idx',
            old_name='core_userset_user_id_idx',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='youtube_enabled',
        ),
        migrations.AlterField(
            model_name='feed',
            name='identifier',
            field=models.TextField(blank=True, default='', help_text='Required for Reddit and YouTube aggregators. For others, optional URL or identifier.'),
        ),
    ]
