# Generated by Django 6.0 on 2026-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_core_userset_user_id_idx_core_userse_user_id_abe139_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
