# Generated by Django 6.0 on 2026-01-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feed_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
    ]
