# Generated by Django 6.0 on 2026-01-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_feed_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='youtube_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
