# Generated by Django 6.0 on 2026-01-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usersettings_youtube_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='icon',
        ),
    ]
