# Generated by Django 6.0 on 2026-01-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_feed_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='daily_limit',
            field=models.IntegerField(default=20),
        ),
    ]
