# Generated by Django 6.0 on 2026-01-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_feed_daily_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='feed_icons/'),
        ),
    ]
