# Generated by Django 6.0 on 2026-01-03

from django.db import migrations


def create_periodic_tasks(apps, schema_editor):
    """Create periodic tasks for feed aggregation, cleanup, and optimization."""
    Schedule = apps.get_model("django_q", "Schedule")

    # Task 1: Feed Aggregation (every 30 minutes) - CRITICAL
    func_name = "core.services.aggregator_service.AggregatorService.trigger_all"
    if not Schedule.objects.filter(func=func_name).exists():
        Schedule.objects.create(
            func=func_name,
            name="Aggregate All Feeds",
            schedule_type="I",  # MINUTES type
            minutes=30,
            repeats=-1,  # Forever
        )

    # Task 2: Article Cleanup (daily)
    func_name = "core.services.article_service.ArticleService.delete_old_articles"
    if not Schedule.objects.filter(func=func_name).exists():
        Schedule.objects.create(
            func=func_name,
            name="Cleanup Old Articles",
            schedule_type="D",  # DAILY type
            repeats=-1,  # Forever
            kwargs='{"months": 2}',  # JSON string format
        )

    # Task 3: SQLite Optimization (weekly)
    func_name = "core.services.maintenance_service.MaintenanceService.optimize_sqlite"
    if not Schedule.objects.filter(func=func_name).exists():
        Schedule.objects.create(
            func=func_name,
            name="Optimize SQLite Database",
            schedule_type="W",  # WEEKLY type
            repeats=-1,  # Forever
        )


def delete_periodic_tasks(apps, schema_editor):
    """Remove periodic tasks (reverse migration)."""
    Schedule = apps.get_model("django_q", "Schedule")

    # Delete all three tasks
    func_names = [
        "core.services.aggregator_service.AggregatorService.trigger_all",
        "core.services.article_service.ArticleService.delete_old_articles",
        "core.services.maintenance_service.MaintenanceService.optimize_sqlite",
    ]

    Schedule.objects.filter(func__in=func_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_feed_icon"),
        ("django_q", "__latest__"),
    ]

    operations = [
        migrations.RunPython(create_periodic_tasks, delete_periodic_tasks),
    ]
