# Generated by Django 6.0 on 2026-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_setup_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Aggregator-specific configuration'),
        ),
    ]
