# Generated by Django 6.0 on 2026-01-04 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_feed_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', 'read', 'date'], name='core_articl_feed_id_9fce98_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['aggregator'], name='core_feed_aggrega_17021e_idx'),
        ),
    ]
