# Generated by Django 6.0 on 2026-01-04 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_article_core_articl_feed_id_9fce98_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditSubreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subscribers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['display_name'], name='core_reddit_display_82c14b_idx')],
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='reddit_subreddit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.redditsubreddit'),
        ),
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='core_youtub_title_8747b5_idx')],
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='youtube_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.youtubechannel'),
        ),
    ]
