# Generated by Django 6.0 on 2026-01-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_redditsubreddit_feed_reddit_subreddit_youtubechannel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='handle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
