# Generated by Django 6.0 on 2026-01-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_youtubechannel_handle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubechannel',
            options={'ordering': ['title'], 'verbose_name': 'YouTube Channel', 'verbose_name_plural': 'YouTube Channels'},
        ),
    ]
