# Generated by Django 6.0 on 2026-01-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_youtubechannel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redditsubreddit',
            options={'ordering': ['display_name'], 'verbose_name': 'Reddit Subreddit', 'verbose_name_plural': 'Reddit Subreddits'},
        ),
    ]
