# Generated by Django 6.0 on 2026-01-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_redditsubreddit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='icon',
        ),
    ]
