# Generated by Django 6.0 on 2026-01-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_feed_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="ai_model",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="active_ai_provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Gemini"),
                ],
                default="openai",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="anthropic_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="anthropic_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="anthropic_model",
            field=models.CharField(
                choices=[
                    ("claude-3-5-sonnet-20240620", "Claude 3.5 Sonnet"),
                    ("claude-3-opus-20240229", "Claude 3 Opus"),
                    ("claude-3-sonnet-20240229", "Claude 3 Sonnet"),
                    ("claude-3-haiku-20240307", "Claude 3 Haiku"),
                ],
                default="claude-3-5-sonnet-20240620",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gemini_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gemini_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gemini_model",
            field=models.CharField(
                choices=[
                    ("gemini-1.5-pro", "Gemini 1.5 Pro"),
                    ("gemini-1.5-flash", "Gemini 1.5 Flash"),
                    ("gemini-1.0-pro", "Gemini 1.0 Pro"),
                ],
                default="gemini-1.5-flash",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="openai_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o", "GPT-4o"),
                    ("gpt-4o-mini", "GPT-4o Mini"),
                    ("gpt-4-turbo", "GPT-4 Turbo"),
                    ("gpt-3.5-turbo", "GPT-3.5 Turbo"),
                    ("o1-preview", "o1 Preview"),
                    ("o1-mini", "o1 Mini"),
                ],
                default="gpt-4o-mini",
                max_length=100,
            ),
        ),
    ]
