# Generated by Django 6.0 on 2026-01-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_usersettings_ai_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="active_ai_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Gemini"),
                ],
                default=None,
                help_text="Select an AI provider to enable AI features. Leave blank to disable.",
                max_length=50,
                null=True,
            ),
        ),
    ]
