# Generated by Django 6.0 on 2026-01-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_usersettings_active_ai_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="active_ai_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Gemini"),
                ],
                default="",
                help_text="Select an AI provider to enable AI features. Leave blank to disable.",
                max_length=50,
            ),
        ),
    ]
