# Generated by Django 6.0 on 2026-02-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_usersettings_active_ai_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ai_request_delay',
            field=models.IntegerField(default=2, help_text='Delay in seconds between AI API calls to avoid rate limits.'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-3-pro-preview', 'Gemini 3 Pro Preview'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash-Lite'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-1.0-pro', 'Gemini 1.0 Pro')], default='gemini-1.5-flash', max_length=100),
        ),
    ]
