# Generated by Django 6.0 on 2026-07-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_migrate_selector_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at', '-id'], name='core_articl_created_63f4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['feed', '-created_at'], name='core_articl_feed_id_8b36fa_idx'),
        ),
    ]
