# Generated by Django 6.0 on 2026-07-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_drop_legacy_drizzle_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='logo',
            field=models.ImageField(blank=True, help_text='Resolved feed logo. Refresh via the admin action.', null=True, upload_to='feed_logos/'),
        ),
        migrations.AddField(
            model_name='feed',
            name='logo_source_url',
            field=models.TextField(blank=True, default='', help_text='URL the logo was resolved from, kept for re-resolution.'),
        ),
    ]
