# Generated by Django 6.0 on 2026-07-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20260730_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plain_text',
            field=models.TextField(blank=True, default='', help_text='Block tree flattened to visible text, for search'),
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('paragraph', 'paragraph'), ('heading', 'heading'), ('list', 'list'), ('list_item', 'list_item'), ('blockquote', 'blockquote'), ('image', 'image'), ('embed', 'embed'), ('code_block', 'code_block'), ('divider', 'divider')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ordered', models.BooleanField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('image_ref', models.TextField(blank=True, default='')),
                ('embed_provider', models.CharField(blank=True, default='', max_length=20)),
                ('embed_thumbnail_ref', models.TextField(blank=True, default='')),
                ('embed_external_url', models.TextField(blank=True, default='')),
                ('embed_title', models.TextField(blank=True, default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.articleblock')),
            ],
            options={
                'verbose_name': 'Article Block',
                'verbose_name_plural': 'Article Blocks',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ArticleInlineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('bold', models.BooleanField(default=False)),
                ('italic', models.BooleanField(default=False)),
                ('code', models.BooleanField(default=False)),
                ('strikethrough', models.BooleanField(default=False)),
                ('link', models.TextField(blank=True, default='')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.articleblock')),
            ],
            options={
                'verbose_name': 'Article Inline Run',
                'verbose_name_plural': 'Article Inline Runs',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='articleblock',
            index=models.Index(fields=['article', 'parent', 'position'], name='core_articl_article_2feefb_idx'),
        ),
        migrations.AddIndex(
            model_name='articleblock',
            index=models.Index(fields=['image_ref'], name='core_articl_image_r_faa157_idx'),
        ),
        migrations.AddIndex(
            model_name='articleblock',
            index=models.Index(fields=['embed_provider'], name='core_articl_embed_p_369c4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='articleblock',
            constraint=models.UniqueConstraint(fields=('article', 'parent', 'position'), name='uniq_block_position'),
        ),
        migrations.AddIndex(
            model_name='articleinlinerun',
            index=models.Index(fields=['block', 'position'], name='core_articl_block_i_2f9aec_idx'),
        ),
    ]
