# Generated by Django 6.0 on 2026-07-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_ai_request_delay'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='greaderauthtoken',
            name='core_greade_token_ec6b6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='greaderauthtoken',
            name='core_greade_user_id_ccd9f7_idx',
        ),
        migrations.DeleteModel(
            name='GReaderAuthToken',
        ),
    ]
