# Generated by Django 6.0 on 2026-07-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_feed_aggregator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='aggregator',
            field=models.CharField(choices=[('full_website', 'Full Website'), ('feed_content', 'Feed Content (RSS/Atom)'), ('heise', 'Heise'), ('merkur', 'Merkur'), ('tagesschau', 'Tagesschau'), ('explosm', 'Explosm'), ('dark_legacy', 'Dark Legacy Comics'), ('caschys_blog', "Caschy's Blog"), ('mactechnews', 'MacTechNews'), ('oglaf', 'Oglaf'), ('mein_mmo', 'Mein-MMO'), ('the_verge', 'The Verge'), ('ars_technica', 'Ars Technica'), ('youtube', 'YouTube'), ('reddit', 'Reddit'), ('podcast', 'Podcast')], default='full_website', max_length=50),
        ),
    ]
