# Generated by Django 6.0 on 2026-07-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_feed_logo'),
        ('core', '0033_drop_oglaf_convert_to_base64'),
    ]

    operations = [
    ]
