import { createDeviceSession } from "@/lib/auth/server";
import { requireUser } from "@/lib/auth/session";

/**
 * The only scheme a real device registers today. A fixed allow-list rather
 * than accepting whatever the caller sends -- see the module doc below.
 */
const ALLOWED_SCHEMES = new Set(["yana"]);

/**
 * The webview's landing point right after the user signs in through the
 * ordinary `/login` form (whose `next` param carries this route's full query
 * string through unchanged) -- session-cookie-authenticated like every other
 * page in `(app)`. There is no separate auth mechanism for pairing.
 *
 * **`state` is generated by the app, not this server, and this route never
 * validates it against anything -- it only echoes it back.** An earlier
 * version had this server mint and check a `state` value via an
 * unauthenticated `/device/pair/start`; that gave an attacker a valid `state`
 * too, so checking it proved nothing. The real CSRF defense lives on the
 * client: the app generates a random value nobody else can know, and its own
 * callback handler only trusts a response whose echoed `state` matches what
 * it's currently expecting. `sessions`' `SameSite=Lax` cookie still lets an
 * attacker's crafted link trigger the *server-side mint* below (there's no
 * way to prevent that without breaking the top-level-navigation webview
 * handoff itself) -- but that mint is harmless on its own: nothing uses the
 * resulting token unless some app's callback handler accepts it, and a
 * legitimate app never accepts an unsolicited callback. See
 * `docs/superpowers/specs/2026-08-03-client-api-design.md` §1.
 *
 * **Order of operations:**
 * 1. `requireUser()` first -- the same principle the avatar route documents:
 *    no answer this route gives to a signed-out caller may depend on what
 *    they asked for.
 * 2. `state` must be present (non-empty) -- refused otherwise, but this is a
 *    presence check only, never a lookup.
 * 3. `scheme` is checked against `ALLOWED_SCHEMES`, never accepted as an
 *    arbitrary client-supplied value.
 * 4. The redirect URL is built and validated.
 * 5. **Only then** is the device session minted -- closes a mint-then-fail
 *    hazard where a bad `scheme` could otherwise leave an orphaned-but-valid,
 *    never-delivered session row behind.
 *
 * The redirect target is a custom URL scheme the native app registers and
 * intercepts before it ever becomes a real network request
 * (`decidePolicyForNavigationAction` on the WKWebView side). The minted token
 * is a genuine, independent Better Auth session -- the same credential
 * `src/lib/api/auth.ts` resolves on every `/api/v1/**` request -- not a
 * separate "API key" concept.
 */
export async function GET(request: Request): Promise<Response> {
  const user = await requireUser();

  const url = new URL(request.url);
  const state = url.searchParams.get("state");
  const scheme = url.searchParams.get("scheme") || "yana";
  const deviceName = url.searchParams.get("deviceName") || "Unnamed device";

  if (!state || !ALLOWED_SCHEMES.has(scheme)) {
    return new Response(null, { status: 400 });
  }

  let callback: URL;
  try {
    // `scheme` is already restricted to `ALLOWED_SCHEMES` above, so this can
    // only fail if a future allow-list entry turns out not to parse as a URL
    // scheme -- kept as defense-in-depth against that.
    callback = new URL(`${scheme}://auth-callback`);
  } catch {
    return new Response(null, { status: 400 });
  }

  const { token } = await createDeviceSession(user.id, deviceName);
  callback.searchParams.set("token", token);
  callback.searchParams.set("state", state);

  return Response.redirect(callback.toString(), 307);
}
