"""
Django settings for yana project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Environment variables are loaded from .env file using django-environ.
See .env.example for all available settings.
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ with defaults
# All settings have sensible defaults and can be overridden via .env file
env = environ.Env(
    # Security
    DEBUG=(bool, True),
    SECRET_KEY=(str, "django-insecure-l4x)1=)q58u$0#n^r1pgnt29y)-k%z2y(0h0tud&3)4533!ikb"),
    # Network
    ALLOWED_HOSTS=(str, "localhost,127.0.0.1"),
    BASE_URL=(str, "http://localhost:8000"),
    # Internationalization
    TIME_ZONE=(str, "UTC"),
    # Email
    EMAIL_HOST=(str, ""),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
    EMAIL_HOST_USER=(str, ""),
    EMAIL_HOST_PASSWORD=(str, ""),
    DEFAULT_FROM_EMAIL=(str, "noreply@localhost"),
    SERVER_EMAIL=(str, "server@localhost"),
    ADMIN_EMAIL=(str, ""),
)

# Read environment file (.env) if it exists
# Variables in .env override defaults above
env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = [host.strip() for host in env("ALLOWED_HOSTS").split(",")]

# CSRF Trusted Origins for production
CSRF_TRUSTED_ORIGINS = [
    f"https://{host.strip()}" for host in env("ALLOWED_HOSTS").split(",") if host.strip() != "*"
]
# Support for proxies
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Secure cookies in production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    SECURE_REDIRECT_EXEMPT = [r"^health/$"]
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

BASE_URL = env("BASE_URL").rstrip("/")


# Application definition

INSTALLED_APPS = [
    "dal",  # django-autocomplete-light (must be before admin)
    "dal_select2",  # django-autocomplete-light with Select2 (must be before admin)
    "django_q",  # Background tasks (supervisor manages qcluster in Docker)
    "core",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "djangoql",
    "import_export",  # Model-level data import and export
]

# Django Import Export Configuration
# https://django-import-export.readthedocs.io/en/stable/configuration.html
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "yana.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "yana.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Using optimized SQLite backend with performance PRAGMA settings:
# - WAL mode for better concurrency
# - Increased cache size (64MB)
# - Memory-mapped I/O (256MB)
# - Optimized synchronous mode
# See core/db/backends.py for details

DATABASES = {
    "default": {
        "ENGINE": "core.db.backends.sqlite3",
        "NAME": BASE_DIR / "data" / "db.sqlite3",
        "OPTIONS": {
            # Connection timeout in seconds (prevents "database is locked" errors)
            "timeout": 30,
            # Check same thread (set to False for better performance in multi-threaded apps)
            # Note: Django Q2 uses multiple threads, so we set this to False
            "check_same_thread": False,
            # Use BEGIN IMMEDIATE for write transactions instead of the default
            # DEFERRED mode. This is the key fix for "database is locked"
            # (SQLITE_BUSY) errors under concurrent writers (e.g. multiple
            # Django Q2 workers + web requests).
            #
            # In WAL mode with DEFERRED transactions, a connection first takes a
            # read lock and only upgrades to a write lock on its first write.
            # If two connections both hold a read lock and try to upgrade, SQLite
            # returns SQLITE_BUSY *immediately* to avoid a deadlock -- ignoring
            # busy_timeout entirely. IMMEDIATE acquires the write lock up front,
            # so busy_timeout is honored and connections queue instead of failing.
            #
            # Supported since Django 5.1. See:
            # https://docs.djangoproject.com/en/stable/ref/databases/#sqlite-isolation
            "transaction_mode": "IMMEDIATE",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django Q2 Configuration
# https://django-q2.readthedocs.io/en/stable/configure.html

Q_CLUSTER = {
    "name": "yana",
    "workers": 4,
    "recycle": 500,
    "timeout": 300,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q2",
    "redis": None,  # Use ORM broker (database) instead of Redis
    "orm": "default",  # Use the default database connection
    "retry": 360,  # Retry failed tasks for 6 minutes
    "max_attempts": 3,  # Maximum retry attempts
    "ack_failures": True,  # Acknowledge failed tasks
    "sync": False,  # Run asynchronously (set to True for testing)
}


# Email Configuration
# https://docs.djangoproject.com/en/6.0/topics/email/

# Email backend - always use SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# SMTP Configuration
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_USE_SSL = env("EMAIL_USE_SSL")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

# Email addresses
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = env("SERVER_EMAIL")

# Admins - receive error notifications via email
# Set ADMIN_EMAIL in .env to enable error email notifications
ADMINS = []
admin_email = env("ADMIN_EMAIL")
if admin_email:
    # Parse comma-separated list of admin emails
    # Format: "Name <email@example.com>, Name2 <email2@example.com>"
    # Or just: "email@example.com, email2@example.com"
    admin_entries = [entry.strip() for entry in admin_email.split(",")]
    for entry in admin_entries:
        if "<" in entry and ">" in entry:
            # Format: "Name <email@example.com>"
            name = entry.split("<")[0].strip()
            email = entry.split("<")[1].split(">")[0].strip()
            ADMINS.append((name, email))
        else:
            # Format: "email@example.com"
            ADMINS.append(("Admin", entry.strip()))

MANAGERS = ADMINS

# Email timeout (seconds)
EMAIL_TIMEOUT = 10


# Logging Configuration
# https://docs.djangoproject.com/en/6.0/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
        "core": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django_q": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
