// src/lib/api/docs/narrative.ts

/**
 * English only, by explicit exception -- this is developer reference
 * material, not product UI, so it does not go through messages/en.json or
 * de.json and src/i18n/messages.test.ts's parity check does not apply to it.
 * See the "Global Constraints" section of this feature's implementation plan.
 */
export const OVERVIEW_MARKDOWN = `
# Yana Client API

The versioned HTTP API a native client (or the web UI itself, for images)
uses to read and modify a signed-in user's feeds, tags, articles and AI
configuration. \`v1\` is the only version today.

**Base URL**: this server's own origin, e.g. \`https://yana.example.com\`.

**Errors** always take the shape \`{ "error": { "code": "...", "message": "..." } }\`.
\`code\` is stable and machine-readable; \`message\` is written by the server
for a human and never echoes anything the caller submitted. See the Errors
section below for the full code index.

**Dates** are always ISO 8601 (\`Date.prototype.toISOString()\`).
`.trim();

export const TAG_DESCRIPTIONS: Record<string, string> = {
  "Auth & pairing": `
The native client obtains a device session via \`GET /device/pair\`, reached
from \`/login\`'s \`next\` parameter after the user signs in through the
ordinary web form inside a pairing webview. The resulting Bearer token is
what every other \`/api/v1/**\` route (except \`/device/pair\` itself, which
uses the signed-in web session) accepts in \`Authorization: Bearer <token>\`.

\`state\` is generated by the app and never validated server-side beyond
presence -- CSRF protection is the app's own responsibility (only the
app's own callback handler knows the \`state\` value it's currently
expecting).

\`POST /api/v1/auth/webview-session-token\` + \`GET /webview-session\` is a
second, independent flow: it lets the native client bootstrap the *same*
device session into a \`WKWebView\`'s cookie jar, so \`ManagementWebView\`
can reach the web UI directly without the app ever touching a password or
passkey.
`.trim(),

  Sync: `
\`GET /api/v1/articles/sync\` returns three independently-cursored deltas:
\`new\`, \`updated\`, \`removed\`. The opaque \`cursor\` string encodes a
\`[timestamp, id]\` position per stream; pass back the previous response's
\`nextCursor\` on the next call, or omit it to sync from the beginning.

\`limit\` caps rows *per stream* per call (default 200, clamped to
\`[1, 500]\`) -- a large backlog is paged across multiple calls, each
advancing that stream's cursor independently of the others.

A response of \`{ "resyncRequired": true }\` means the cursor is older than
the server's tombstone-retention horizon: some deletion between the cursor
and now may have already been pruned without a trace, so the client must
discard its local state and sync from the beginning (omit \`cursor\`)
rather than trust a possibly-incomplete \`removed\` list.
`.trim(),

  "Reading position": `
A single cross-device "what article am I reading" pointer per user, backed
by two columns on their settings row -- not a history, just the current
position. \`PATCH\` is last-writer-wins across devices; there is no
conflict resolution beyond "the most recent write's timestamp wins."

Every device with an open \`GET /api/v1/jobs/events\` connection receives a
\`readingPosition\` event immediately after another device's \`PATCH\`, so
open apps can jump live instead of waiting for their next poll of this
endpoint.
`.trim(),

  Jobs: `
\`GET /api/v1/jobs/events\` is a single long-lived Server-Sent-Events
connection carrying three event types for the caller:

- \`job\` -- one background job's status/progress changed.
- \`run\` -- a run's aggregate counters changed (see \`POST /api/v1/aggregate\`).
- \`readingPosition\` -- another device moved the reading-position pointer.

This is a best-effort, low-latency notification layer, not the source of
truth: a dropped connection loses nothing except immediacy. A reconnecting
client should always re-poll \`GET /api/v1/runs/{id}\` (or
\`GET /api/v1/reading-position\`) to recover its actual current state, since
events missed while disconnected are not replayed. The server sends an SSE
comment ping every 15 seconds to keep intermediary proxies from treating a
quiet connection as dead; conforming SSE clients ignore comment lines.

**The event type is carried in the SSE \`event:\` line, never in the JSON
body.** Each \`data:\` frame is the bare payload only (job/run/reading-position
fields, with no \`type\` discriminant) -- read which of the three event types
it is from \`event:\`, not from the parsed JSON.
`.trim(),
};

export const CONVENTIONS_MARKDOWN = `
## Conventions

- **Dates** are always ISO 8601 (\`Date.prototype.toISOString()\`).
- **Pagination**: \`GET /api/v1/articles/sync\` is the only paginated endpoint. \`limit\`
  caps rows *per stream* per call (default 200, clamped to \`[1, 500]\`), and \`cursor\` is
  opaque -- pass back the previous response's \`nextCursor\` to continue.
- **Not found vs. forbidden**: every ownership check answers 404, never 403, for a row
  that exists but isn't the caller's -- this prevents an authenticated caller from
  learning that a given id exists at all through the response code alone.
`.trim();
